### ISSUE TITLE
Can't pass both byprobe and bycountry to summary.average

### ISSUE THREAD

**Issue by duien** [mtodd/pingdom-client#2]
The default :byprobe option should only be used if :bycountry is not set

```
ruby-1.8.7-p302 > $client.checks.first.summary.average :bycountry => true
Pingdom::Error: bycountry and byprobe can not both be set to true (400 Bad Request)
    from ./lib/pingdom/base.rb:42:in `check_error!'
    from ./lib/pingdom/base.rb:49:in `parse'
    from ./lib/pingdom/summary/average.rb:12:in `parse'
    from ./lib/pingdom/summary.rb:8:in `average'
    from (irb):1
```

**Comment by mtodd** [comment]
For now the workaround is to also specify `:byprobe` to false.
